/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class menuPesanTiket extends javax.swing.JFrame {
    int royal, eksekutif, a, b, c;
    String royalS, eksekutifS;
    private String tanggal, jenisBus;
   
    /**
     * Creates new form menuPesanTiket
     */
    public menuPesanTiket() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        judulProgram = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        pilihJurusan = new javax.swing.JComboBox<>();
        pilihRoyal = new javax.swing.JRadioButton();
        pilihEksekutif = new javax.swing.JRadioButton();
        isiNomorBis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        isiNama = new javax.swing.JTextField();
        txt7 = new javax.swing.JLabel();
        isiKursi = new javax.swing.JTextField();
        txt8 = new javax.swing.JLabel();
        isiJumlahTiket = new javax.swing.JTextField();
        txt9 = new javax.swing.JLabel();
        txt10 = new javax.swing.JLabel();
        isiBayar = new javax.swing.JTextField();
        txt11 = new javax.swing.JLabel();
        isiKembalian = new javax.swing.JTextField();
        txt6 = new javax.swing.JLabel();
        txt13 = new javax.swing.JLabel();
        isiNomorHp = new javax.swing.JTextField();
        txt12 = new javax.swing.JLabel();
        isiTotal = new javax.swing.JTextField();
        isiTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilCetak = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        txt14 = new javax.swing.JLabel();
        txt16 = new javax.swing.JLabel();
        txt17 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        isiHarga = new javax.swing.JTextField();
        tampilJurusan = new javax.swing.JTextField();
        tampilJurusan2 = new javax.swing.JTextField();
        txt15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(36, 69, 90));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 1, 37)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MY DEMRI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        judulProgram.setBackground(new java.awt.Color(255, 255, 255));
        judulProgram.setFont(new java.awt.Font("Futura Bk BT", 1, 26)); // NOI18N
        judulProgram.setText("Pesan Tiket");

        jSeparator1.setBackground(new java.awt.Color(36, 69, 90));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txt1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt1.setText("Jurusan");

        txt2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt2.setText("Jenis");

        txt5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt5.setText("Harga");

        pilihJurusan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pilihJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jurusan", "Pontianak - Ng. Pinoh", "Pontianak - Sintang", "Pontianak - Sekadau", "Pontianak - Sanggau", "Pontianak - Tayan", "Pontianak - Ketapang" }));
        pilihJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihJurusanActionPerformed(evt);
            }
        });

        pilihRoyal.setBackground(new java.awt.Color(255, 255, 255));
        pilihRoyal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pilihRoyal.setText("Royal");
        pilihRoyal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihRoyalActionPerformed(evt);
            }
        });

        pilihEksekutif.setBackground(new java.awt.Color(255, 255, 255));
        pilihEksekutif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pilihEksekutif.setText("Eksekutif");
        pilihEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihEksekutifActionPerformed(evt);
            }
        });

        isiNomorBis.setEditable(false);
        isiNomorBis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiNomorBis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiNomorBisActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        isiNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiNamaActionPerformed(evt);
            }
        });

        txt7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt7.setText("Nomor Kursi");

        isiKursi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiKursiActionPerformed(evt);
            }
        });
        isiKursi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiKursiKeyTyped(evt);
            }
        });

        txt8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt8.setText("Jumlah Tiket");

        isiJumlahTiket.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiJumlahTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiJumlahTiketActionPerformed(evt);
            }
        });
        isiJumlahTiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiJumlahTiketKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiJumlahTiketKeyTyped(evt);
            }
        });

        txt9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt9.setText("Tanggal Berangkat");

        txt10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt10.setText("Uang Bayar");

        isiBayar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiBayarActionPerformed(evt);
            }
        });
        isiBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiBayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiBayarKeyTyped(evt);
            }
        });

        txt11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt11.setText("Uang Kembalian");

        isiKembalian.setEditable(false);
        isiKembalian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiKembalianActionPerformed(evt);
            }
        });

        txt6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt6.setText("Nama Penumpang");

        txt13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt13.setText("Nomor Telepon");

        isiNomorHp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiNomorHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiNomorHpActionPerformed(evt);
            }
        });
        isiNomorHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiNomorHpKeyTyped(evt);
            }
        });

        txt12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt12.setText("Total");

        isiTotal.setEditable(false);
        isiTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiTotalActionPerformed(evt);
            }
        });

        isiTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                isiTanggalPropertyChange(evt);
            }
        });

        tampilCetak.setEditable(false);
        tampilCetak.setColumns(20);
        tampilCetak.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tampilCetak.setRows(5);
        jScrollPane1.setViewportView(tampilCetak);

        cetak.setBackground(new java.awt.Color(36, 69, 90));
        cetak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cetak.setForeground(new java.awt.Color(255, 255, 255));
        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(36, 69, 90));
        hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Reset");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        kembali.setBackground(new java.awt.Color(36, 69, 90));
        kembali.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        txt14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt14.setText("Rp");

        txt16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt16.setText("Rp");

        txt17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt17.setText("Rp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt6)
                            .addComponent(txt7)
                            .addComponent(txt13)
                            .addComponent(txt10)
                            .addComponent(txt11)
                            .addComponent(txt12)
                            .addComponent(txt8))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isiKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(isiJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiNomorHp)
                            .addComponent(isiNama)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt17)
                            .addComponent(txt16)
                            .addComponent(txt14))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isiBayar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isiKembalian, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isiTotal, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembali)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt7)
                            .addComponent(isiKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt13)
                            .addComponent(isiNomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txt9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(isiTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt10)
                                .addComponent(txt14))
                            .addComponent(isiBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt16)
                            .addComponent(txt11))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt17)
                            .addComponent(txt12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cetak)
                                .addGap(18, 18, 18)
                                .addComponent(hapus)
                                .addGap(18, 18, 18)
                                .addComponent(kembali)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt3.setText("Nomor");

        isiHarga.setEditable(false);
        isiHarga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isiHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiHargaActionPerformed(evt);
            }
        });

        tampilJurusan.setEditable(false);
        tampilJurusan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tampilJurusan.setForeground(new java.awt.Color(255, 255, 255));
        tampilJurusan.setBorder(null);
        tampilJurusan.setCaretColor(new java.awt.Color(255, 255, 255));
        tampilJurusan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tampilJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilJurusanActionPerformed(evt);
            }
        });
        tampilJurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tampilJurusanKeyTyped(evt);
            }
        });

        tampilJurusan2.setEditable(false);
        tampilJurusan2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tampilJurusan2.setForeground(new java.awt.Color(255, 255, 255));
        tampilJurusan2.setBorder(null);
        tampilJurusan2.setCaretColor(new java.awt.Color(255, 255, 255));
        tampilJurusan2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tampilJurusan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilJurusan2ActionPerformed(evt);
            }
        });
        tampilJurusan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tampilJurusan2KeyTyped(evt);
            }
        });

        txt15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt15.setText("Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt1)
                    .addComponent(txt2)
                    .addComponent(txt3)
                    .addComponent(txt5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihRoyal)
                    .addComponent(isiNomorBis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihEksekutif)
                    .addComponent(pilihJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilJurusan2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(isiHarga))
                        .addComponent(tampilJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judulProgram))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(judulProgram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1)
                            .addComponent(pilihJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2)
                            .addComponent(pilihRoyal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihEksekutif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiNomorBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5)
                            .addComponent(txt15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tampilJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tampilJurusan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihRoyalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihRoyalActionPerformed
        // harga tiket bis jenis royal
        if (pilihRoyal.isSelected()) {
            isiHarga.setText(String.valueOf(royal));
            isiNomorBis.setText(String.valueOf(royalS));
        }
        // menampilkan royal ke txtfield tampiljurusan2
        jenisBus = "Royal";
        pilihEksekutif.setSelected(false);
        tampilJurusan2.setText(jenisBus);
    }//GEN-LAST:event_pilihRoyalActionPerformed

    private void isiNomorBisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiNomorBisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiNomorBisActionPerformed

    private void isiNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiNamaActionPerformed

    private void isiKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiKursiActionPerformed

    private void isiJumlahTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiJumlahTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiJumlahTiketActionPerformed

    private void isiBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiBayarActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_isiBayarActionPerformed

    private void isiKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiKembalianActionPerformed

    private void isiTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiTotalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // menghapus
        isiHarga.setText("");
        pilihJurusan.setSelectedItem("Pilih Jurusan");
        isiNomorBis.setText("");
        isiNama.setText("");
        isiKursi.setText("");
        isiNomorHp.setText("");
        isiJumlahTiket.setText("");
        isiBayar.setText("");
        isiKembalian.setText("");
        isiTotal.setText("");
        tampilCetak.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void pilihJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihJurusanActionPerformed
        //menentukan harga sesuai jurusan
        if (pilihJurusan.getSelectedItem().equals("Pilih Jurusan")) {     
            isiHarga.setText("");
            isiNomorBis.setText("");
        }
        else if(pilihJurusan.getSelectedItem().equals("Pontianak - Ng. Pinoh")) {
            royal = 210000;
            royalS = "1A";
            eksekutif = 170000;
            eksekutifS = "1B";
        }
         else if(pilihJurusan.getSelectedItem().equals("Pontianak - Sintang")) {
            royal = 200000;
            royalS = "2A";
            eksekutif = 150000;
            eksekutifS = "2B";
        }
         else if(pilihJurusan.getSelectedItem().equals("Pontianak - Sekadau")) {
            royal = 170000;
            royalS = "3A";
            eksekutif = 140000;
            eksekutifS = "3B";
        }
         else if(pilihJurusan.getSelectedItem().equals("Pontianak - Sanggau")) {
            royal = 100000;
            royalS = "4A";
            eksekutif = 75000;
            eksekutifS = "4B";
        }
         else if(pilihJurusan.getSelectedItem().equals("Pontianak - Tayan")) {
            royal = 130000;
            royalS = "5A";
            eksekutif = 100000;
            eksekutifS = "5B";
        }
         else if(pilihJurusan.getSelectedItem().equals("Pontianak - Ketapang")) {
            royal = 240000;
            royalS = "6A";
            eksekutif = 200000;
            eksekutifS = "6B";
        }
        //menampilkan jurusan yang dipilih ke txtfieldtampilJurusan
        String selectedValue = pilihJurusan.getSelectedItem().toString();
        tampilJurusan.setText(selectedValue);
    }//GEN-LAST:event_pilihJurusanActionPerformed

    private void isiHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiHargaActionPerformed

    private void pilihEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihEksekutifActionPerformed
        // harga tiket bis jenis eksekutif
         if (pilihEksekutif.isSelected()) {
            isiHarga.setText(String.valueOf(eksekutif));
            isiNomorBis.setText(String.valueOf(eksekutifS));
        }
        // menampilkan eksekutif ke txtfield tampiljurusan2
        jenisBus = "Eksekutif";
        pilihRoyal.setSelected(false);
        tampilJurusan2.setText(jenisBus);
    }//GEN-LAST:event_pilihEksekutifActionPerformed

    private void isiJumlahTiketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiJumlahTiketKeyReleased
        // jumlah tiket yg akan dibeli (akan langsung ditampilkan di total)
        a = Integer.valueOf(isiHarga.getText());
        b = Integer.valueOf(isiJumlahTiket.getText());
        c = a * b;
        isiTotal.setText("" + c);
    }//GEN-LAST:event_isiJumlahTiketKeyReleased

    private void isiBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiBayarKeyReleased
         // uang yang dibayar pembeli (akan langsung ditampilkan di total)
        a = Integer.valueOf(isiBayar.getText());
        b = Integer.valueOf(isiTotal.getText());
        c = a - b;
        isiKembalian.setText("" + c);
    }//GEN-LAST:event_isiBayarKeyReleased

    private void isiNomorHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiNomorHpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_isiNomorHpActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // kembali ke menu sebelumnya
        this.hide();
        menuUtama kembali = new menuUtama();
        kembali.setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // menampilkan data data yang sudah diisi
        tampilCetak.setText(
            "                   BUS DEMRI" + "\n" + 
            "                 Tiket Penumpang"  + "\n" + "\n" +
            "Jurusan Bus           : " + tampilJurusan.getText() + "\n" +
            "Jenis Bus             : " + tampilJurusan2.getText() + "\n" + 
            "Nomor Bus             : " + isiNomorBis.getText() + "\n" +
            "Harga Tiket           : " + "Rp" + isiHarga.getText() + "\n" +
            "----------------------------------------------" + "\n" +
            "Nama Penumpang        : " + isiNama.getText() + "\n" +
            "Nomor Kursi           : " + isiKursi.getText() + "\n" +
            "Nomor Telepon         : " + isiNomorHp.getText() + "\n" +
            "Jumlah Tiket          : " + isiJumlahTiket.getText() + "\n" +
            "Tanggal Keberangkatan : " + tanggal + "\n" +
            "Uang Bayar            : " + "Rp" + isiBayar.getText() + "\n" +
            "Uang Kembalian        : " + "Rp" + isiKembalian.getText() + "\n" +
            "Total                 : " + "Rp" + isiTotal.getText() + "\n" + "\n" +
            "  Terima Kasih Sudah Menggunakan Layanan Kami" 
        );
    }//GEN-LAST:event_cetakActionPerformed

    private void isiKursiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKursiKeyTyped
        // hanya dapat diinputkan angka
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_isiKursiKeyTyped

    private void isiNomorHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiNomorHpKeyTyped
        // hanya dapat diinputkan angka
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_isiNomorHpKeyTyped

    private void isiJumlahTiketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiJumlahTiketKeyTyped
        // hanya dapat diinputkan angka
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_isiJumlahTiketKeyTyped

    private void tampilJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilJurusanActionPerformed

    private void tampilJurusanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tampilJurusanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilJurusanKeyTyped

    private void isiTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_isiTanggalPropertyChange
        // TODO add your handling code here:
        if (isiTanggal.getDate()!=null) {
            SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
            tanggal = formatTanggal.format(isiTanggal.getDate());
        }
    }//GEN-LAST:event_isiTanggalPropertyChange

    private void tampilJurusan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilJurusan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilJurusan2ActionPerformed

    private void tampilJurusan2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tampilJurusan2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilJurusan2KeyTyped

    private void isiBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiBayarKeyTyped
       // hanya dapat diinputkan angka
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_isiBayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPesanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField isiBayar;
    private javax.swing.JTextField isiHarga;
    private javax.swing.JTextField isiJumlahTiket;
    private javax.swing.JTextField isiKembalian;
    private javax.swing.JTextField isiKursi;
    private javax.swing.JTextField isiNama;
    private javax.swing.JTextField isiNomorBis;
    private javax.swing.JTextField isiNomorHp;
    private com.toedter.calendar.JDateChooser isiTanggal;
    private javax.swing.JTextField isiTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judulProgram;
    private javax.swing.JButton kembali;
    private javax.swing.JRadioButton pilihEksekutif;
    private javax.swing.JComboBox<String> pilihJurusan;
    private javax.swing.JRadioButton pilihRoyal;
    private javax.swing.JTextArea tampilCetak;
    private javax.swing.JTextField tampilJurusan;
    private javax.swing.JTextField tampilJurusan2;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt13;
    private javax.swing.JLabel txt14;
    private javax.swing.JLabel txt15;
    private javax.swing.JLabel txt16;
    private javax.swing.JLabel txt17;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
